apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapa-interactivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapa-interactivo
  template:
    metadata:
      labels:
        app: mapa-interactivo
    spec:
      containers:
        - name: contenedor-mapa-interactivo
          image: tomicampos22/mapainteractivo:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mapa-interactivo-service
spec:
  type: LoadBalancer
  selector:
    app: mapa-interactivo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
